version: '3.3'
services:
  #-----------------------------------------------------------------------------
  # MANAGEMENT
  #-----------------------------------------------------------------------------

  # --------------------------------------------------------------------------
  # unifi - ubiquiti management controller
  unifi:
    container_name: unifi
    hostname: unifi
    restart: unless-stopped
    networks:
      media-apps-swag_apps: {}
    ports:
      - 5514:5514
      - 3478:3478/udp
      - 6789:6789
      - 8080:8080
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 10001:10001/udp
    environment:
      - TZ=America/New_York
      - BASEDIR=/usr/lib/unifi
      - DATADIR=/unifi/data
      - LOGDIR=/unifi/log
      - CERTDIR=/unifi/cert
      - RUNDIR=/var/run/unifi
      - ODATADIR=/var/lib/unifi
      - OLOGDIR=/var/log/unifi
      - CERTNAME=cert.pem
      - CERT_PRIVATE_NAME=privkey.pem
      - CERT_IS_CHAIN=false
      - GOSU_VERSION=1.10
      - BIND_PRIV=false
      - RUNAS_UID0=false
      - UNIFI_GID=100
      - UNIFI_UID=${PUID}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DIR}/unifi:/unifi
      - /var/run/unifi
    command: unifi
    image: jacobalberty/unifi:latest

  #-----------------------------------------------------------------------------
  # OAUTH and MFA
  #-----------------------------------------------------------------------------
  # Comment or delete this section if you're not interested in oauth or MFA.
  # It is recommended as it adds a layer of security to your applications,
  # specially if they're internet facing.
  #-----------------------------------------------------------------------------

  # redis - session database (more performance)
  # default run PUID is 1001 and PGID is root(0)
  # cant' seem to change it, folder permissions need to be set accordingly
  authredis:
    container_name: authredis
    hostname: authredis
    restart: unless-stopped
    networks:
      media-apps-swag_apps: {}
    environment:
      - TZ=${TZ}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DIR}/authredis:/bitnami/redis/data
      - ${DOCKER_DIR}/authredis/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    secrets:
      - redis
    command: /opt/bitnami/scripts/redis/run.sh --requirepass ${REDIS_PASSWORD}
    image: bitnami/redis:latest

  # mariadb - used for authelia storage
  authmariadb:
    container_name: authmariadb
    hostname: authmariadb
    restart: unless-stopped
    networks:
      media-apps-swag_apps: {}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
      - UMASK=022
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root
      - FILE__MYSQL_PASSWORD=/run/secrets/mysql
      - MYSQL_DATABASE=authelia
      - MYSQL_USER=authelia
    secrets:
      - mysql
      - mysql_root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DIR}/authmariadb:/config
    image: ghcr.io/linuxserver/mariadb:latest

  # Authelia - Self-Hosted Single Sign-On and Two-Factor Authentication
  # Docs: https://www.authelia.com/docs/
  authelia:
    container_name: authelia
    hostname: authelia
    restart: unless-stopped
    networks:
      media-apps-swag_apps: {}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DIR}/authelia:/config
    environment:
      - TZ=${TZ}
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/jwt
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/session
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/mysql
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/smtp
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/duo
      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/run/secrets/redis
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE=/run/secrets/postgress
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/run/secrets/ldap
    secrets:
      - jwt
      - session
      - mysql
      - smtp
      - duo
      - redis
      - postgress
      - ldap
    depends_on:
      - authredis
      - authmariadb
    image: authelia/authelia:4.23

networks:
  media-apps-swag_apps:
    external: true

secrets:
  acme_email:
    file: ${DOCKER_DIR}/secrets/acme_email
  calibre_user:
    file: ${DOCKER_DIR}/secrets/calibre_user
  calibre_pass:
    file: ${DOCKER_DIR}/secrets/calibre_pass
  jwt:
    file: ${DOCKER_DIR}/secrets/jwt
  session:
    file: ${DOCKER_DIR}/secrets/session
  mysql:
    file: ${DOCKER_DIR}/secrets/mysql
  mysql_root:
    file: ${DOCKER_DIR}/secrets/mysql_root
  smtp:
    file: ${DOCKER_DIR}/secrets/smtp
  duo:
    file: ${DOCKER_DIR}/secrets/duo
  plex_claim:
    file: ${DOCKER_DIR}/secrets/plex_claim
  plex_4k_claim:
    file: ${DOCKER_DIR}/secrets/plex_4k_claim
  redis:
    file: ${DOCKER_DIR}/secrets/redis
  postgress:
    file: ${DOCKER_DIR}/secrets/postgress
  ldap:
    file: ${DOCKER_DIR}/secrets/ldap
  authmariadb_root_password:
    file: ${DOCKER_DIR}/secrets/authmariadb_root_password
  maxminddb:
    file: ${DOCKER_DIR}/secrets/maxminddb
